### ISSUE TITLE
Issue with OSError

### ISSUE THREAD

**Issue by Lyn-Ackert-Smith** [cortex-lab/phy#1043]
In response to the phy template-gui params.py command I get the following error, any help would be greatly appreciated!

(phy2) lyns-mbp-5240:Downloads lyn$ phy template-gui params.py
11:20:53.591 [E] __init__:62          An error has occurred (OSError): 
Traceback (most recent call last):
  File "/Users/lyn/anaconda3/envs/phy2/bin/phy", line 8, in <module>
    sys.exit(phycli())
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/__init__.py", line 159, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/template/gui.py", line 198, in template_gui
    controller = TemplateController(model=load_model(params_path), dir_path=dir_path, **kwargs)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phylib/io/model.py", line 1178, in load_model
    return TemplateModel(**get_template_params(params_path))
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phylib/io/model.py", line 297, in __init__
    self._load_data()
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phylib/io/model.py", line 306, in _load_data
    self.spike_samples, self.spike_times = self._load_spike_samples()
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phylib/io/model.py", line 593, in _load_spike_samples
    times = self._read_array(times_path)
  File "/Users/lyn/anaconda3/envs/phy2/lib/python3.7/site-packages/phylib/io/model.py", line 425, in _read_array
    raise IOError()
OSError

**Comment by kevin-lee-ma** [comment]
Did you end up finding out what the issue was? I am having the same problem..

**Comment by rossant** [comment]
This concerns an unsupported Python/phylib stack. Please reopen with a phy 2.1 traceback.
