### ISSUE TITLE
Error in Phy during CAJAL demonstration

### ISSUE THREAD

**Issue by markuspleijzier** [cortex-lab/phy#1162]
`An error has occurred (AssertionError): 
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/plot/base.py", line 778, in wheelEvent
    self.emit('mouse_wheel', pos=pos, delta=deltay, modifiers=modifiers)
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/plot/base.py", line 718, in emit
    f(Bunch(kwargs))
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/cluster/views/correlogram.py", line 304, in on_mouse_wheel
    self.plot()
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/cluster/views/correlogram.py", line 196, in plot
    bunchs = self.get_clusters_data()
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/cluster/views/correlogram.py", line 113, in get_clusters_data
    ccg = self.correlograms(self.cluster_ids, self.bin_size, self.window_size)
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/joblib/memory.py", line 537, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/joblib/memory.py", line 779, in call
    output = self.func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phy/apps/base.py", line 1478, in _get_correlograms
    return correlograms(
  File "/Users/admin/opt/miniconda3/envs/phy/lib/python3.9/site-packages/phylib/stats/ccg.py", line 127, in correlograms
    assert binsize >= 1
AssertionError`

**Comment by hozhabrie** [comment]
having the same issue--how do I fix?
