### ISSUE TITLE
ImportError: DLL load failed while importing _device:

### ISSUE THREAD

**Issue by leterraiozz** [cortex-lab/phy#1182]
Hi, I got this error since I try to use "phy template-gui params.py" command.
I'm running with Python 3.8.13 and Anaconda 2.1.1. 

Traceback (most recent call last):
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\MKP\anaconda3\envs\Phy\Scripts\phy.exe\__main__.py", line 4, in <module>
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\phy\apps\__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\phy\gui\__init__.py", line 12, in <module>
    from .widgets import HTMLWidget, HTMLBuilder, Table, IPythonView, KeyValueWidget
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\phy\gui\widgets.py", line 15, in <module>
    from qtconsole.inprocess import QtInProcessKernelManager
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\qtconsole\inprocess.py", line 5, in <module>
    from ipykernel.inprocess import (
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\zmq\__init__.py", line 125, in <module>
    from zmq import backend
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mkp\anaconda3\envs\Phy\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: 系統無法存取該檔案。

Any idea on what is wrong?

Best!

**Comment by zm711** [comment]
This is two years two late, but we've made some patches to Phy. could you try reinstalling with python3.11?
