### ISSUE TITLE
Missing files in cache folders when using phy on different computer

### ISSUE THREAD

**Issue by guilhemibos** [cortex-lab/phy#1191]
Hi

I'm trying to run phy on a computer (windows) different from the one used for kilosort (KS2, ubuntu). I've copied the directory with Kilosort outputs, as well as the data.dat file on this new computer.

Launching phy works fine, and I'm able to curate and save data normally. However, this error shows up in the command line when I close phy (and an error window pops up too):
[E] __init__:62          An error has occurred (FileNotFoundError): [Errno 2] No such file or directory: '\\\\PATH\\.phy\\memcache\\phy.apps.base.get_mean_spike_template_amplitudes.pkl'
Traceback (most recent call last):
  File "\anaconda3\lib\site-packages\phy\gui\gui.py", line 590, in closeEvent
    res = emit('close', self)
  File "\anaconda3\lib\site-packages\phylib\utils\event.py", line 141, in emit
    res.append(f(sender, *args, **kwargs))
  File "\anaconda3\lib\site-packages\phy\apps\base.py", line 1750, in on_close
    self.context.save_memcache()
  File "\anaconda3\lib\site-packages\phy\utils\context.py", line 139, in save_memcache
    with open(str(path), 'wb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '\\\\PATH\\.phy\\memcache\\phy.apps.base.get_mean_spike_template_amplitudes.pkl'

First, is that a problem regarding saved data?
Second, why does that happen and is it fixable?

Thanks
Guilhem

**Comment by rossant** [comment]
Does this still happen in phy 2.1? If so, please share the data paths and debug output.
