### ISSUE TITLE
ImportError: libasound.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dervinism** [cortex-lab/phy#1204]
Hi,

After following developer installation instructions and attempting to launch Phy, I get the following error:
```
$ phy template-gui params.py
Traceback (most recent call last):
  File "/home/martynas-cph/phy/bin/phy", line 33, in <module>
    sys.exit(load_entry_point('phy', 'console_scripts', 'phy')())
  File "/home/martynas-cph/phy/bin/phy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/apps/__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/gui/__init__.py", line 6, in <module>
    from .qt import (
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/gui/qt.py", line 41, in <module>
    from PyQt5.QtWebEngineWidgets import (QWebEngineView,  # noqa
ImportError: libasound.so.2: cannot open shared object file: No such file or directory
```

**Comment by dervinism** [comment]
I get the same upon regular installation as well.

**Comment by dervinism** [comment]
After installing a missing dependency
```
sudo apt-get install libasound2
```
I get the following error:
```
/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/gloo/variable.py:86: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  gl.GL_BOOL: (1, gl.GL_BOOL, np.bool),
Traceback (most recent call last):
  File "/home/martynas-cph/phy/bin/phy", line 33, in <module>
    sys.exit(load_entry_point('phy', 'console_scripts', 'phy')())
  File "/home/martynas-cph/phy/bin/phy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/apps/__init__.py", line 25, in <module>
    from .base import (  # noqa
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/apps/base.py", line 26, in <module>
    from phy.cluster._utils import RotatingProperty
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/cluster/__init__.py", line 9, in <module>
    from .views import *  # noqa
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/cluster/views/__init__.py", line 10, in <module>
    from .base import ManualClusteringView  # noqa
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/cluster/views/base.py", line 21, in <module>
    from phy.plot import PlotCanvas, NDC, extend_bounds
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/__init__.py", line 17, in <module>
    from .base import BaseVisual, GLSLInserter, BaseCanvas, BaseLayout
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/base.py", line 20, in <module>
    from . import gloo
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/gloo/__init__.py", line 10, in <module>
    from .program import Program
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/gloo/program.py", line 18, in <module>
    from .variable import Uniform, Attribute
  File "/mnt/c/Users/Martynas/Python_libraries/phy/phy/plot/gloo/variable.py", line 86, in <module>
    gl.GL_BOOL: (1, gl.GL_BOOL, np.bool),
  File "/home/martynas-cph/phy/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```
