### ISSUE TITLE
Error when using iPythonView: "AttributeError: 'QtInProcessChannel' object has no attribute 'closed'"

### ISSUE THREAD

**Issue by stef1029** [cortex-lab/phy#1221]
Hello,

When trying to run commands in the iPythonView window in phy2 template GUI I get the following error:

12:40:29.557 [E] __init__:62          An error has occurred (AttributeError): 'QtInProcessChannel' object has no attribute 'closed'
Traceback (most recent call last):
  File "C:\Users\Stefan R Coltman\.conda\envs\phy3\Lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Stefan R Coltman\.conda\envs\phy3\Lib\site-packages\qtconsole\jupyter_widget.py", line 193, in _handle_execute_reply
    super()._handle_execute_reply(msg)
  File "C:\Users\Stefan R Coltman\.conda\envs\phy3\Lib\site-packages\qtconsole\frontend_widget.py", line 468, in _handle_execute_reply
    if not self.kernel_client.iopub_channel.closed():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QtInProcessChannel' object has no attribute 'closed'

The window then freezes and does not allow anything else to be written.

Thanks for any help you can give,

Stefan

**Comment by zm711** [comment]
Hey @stef1029, I'm not super familiar with using the IPython view so the best advice I can at least try to give you is to make sure the package is all up-to-date. Have you recently installed Phy or is this an old install? You're in a conda environment so how did you install phy originally? Do all of the other view work?

**Comment by rossant** [comment]
This should be fixed in phy 2.1. Please reopen if it still happens.
