### ISSUE TITLE
error : phy template-gui params.py

### ISSUE THREAD

**Issue by TNR1073** [cortex-lab/phy#1278]
Hi, everyone. 
I will use phy2 for spike sorting. 
I installed phy2 following the instruction. When I opened GUI, the error shown below occured.
I'm a beginner. So I don't know the solution.
Please tell me if you know how to solve this issue.

>phy template-gui params.py
13:31:08.898 [E] __init__:62          An error has occurred (ImportError): cannot import name '_initialization' from 'statsmodels.tsa.statespace' (C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\statsmodels\tsa\statespace\__init__.py)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ryo_1\anaconda3\envs\test\Scripts\phy.exe\__main__.py", line 7, in <module>
    sys.exit(phycli())
             ^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\phy\apps\__init__.py", line 159, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\phy\apps\template\gui.py", line 209, in template_gui
    model = load_model(params_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\phylib\io\model.py", line 1433, in load_model
    return TemplateModel(**get_template_params(params_path))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\phylib\io\model.py", line 1416, in get_template_params
    params = read_python(params_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\phylib\utils\_misc.py", line 173, in read_python
    exec(contents, {}, metadata)
  File "<string>", line 11, in <module>
  File "C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\statsmodels\tsa\statespace\tools.py", line 14, in <module>
    from . import (_initialization, _representation, _kalman_filter,
ImportError: cannot import name '_initialization' from 'statsmodels.tsa.statespace' (C:\Users\ryo_1\anaconda3\envs\test\Lib\site-packages\statsmodels\tsa\statespace\__init__.py)

QWidget: Must construct a QApplication before a QWidget

**Comment by zm711** [comment]
The error is actually not helpful. But the stack trace is. Why are you trying to import statsmodels? Does your lab have some plugins?

**Comment by TNR1073** [comment]
Thank you for responding.
I misunderstood and used a different kind of file.
I can resolved this problem.
Thanks.
