### ISSUE TITLE
ISIView Changes and AmplitudeView 'template_feature' mode bug

### ISSUE THREAD

**Issue by mswallac** [cortex-lab/phy#877]
Hey Cyrille,

Firstly, I have some issues as well as a suggested addition for ISIView.

- Currently one can set n_bins, bin_size, xmin, and xmax.  This is redundant.  We propose to adopt the options in the correlogram view (bin size and xmax only, with xmin always set to zero)
- If you would like to keep the option for setting xmin to something other thn zero, we note that Xmin seems to increase sometimes after it is set.  We think it automatically increases when there is no data to display in the first bins. 
- When changing bin size, X-minimum, and X-maximum, the default values (current parameters) appear in seconds but the entered text is interpreted in ms.
- Feature addition: Allow for toggling Y-axis between log scale and linear scale

Secondly, the below error occurs when trying to view template_feature mode in AmplitudeView  with a new cluster (one generated by merging or splitting).

```console

[90m14:23:25.087 [D] actions:205          Traceback (most recent call last):
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\gui\actions.py", line 202, in wrapped
    return callback(*args)
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\cluster\views\amplitude.py", line 203, in next_amplitude_type
    self._change_amplitude_type(+1)
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\cluster\views\amplitude.py", line 199, in _change_amplitude_type
    self.plot()
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\cluster\views\amplitude.py", line 167, in plot
    bunchs = self.get_clusters_data()
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\cluster\views\amplitude.py", line 148, in get_clusters_data
    bunchs = self.amplitudes[self.amplitude_name](cluster_ids, load_all=load_all) or ()
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\apps\base.py", line 1176, in _amplitude_getter
    first_cluster=first_cluster)
  File "C:\Users\labadmin\Miniconda3\envs\phy2m\lib\site-packages\joblib\memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\labadmin\Miniconda3\envs\phy2m\lib\site-packages\joblib\memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "C:\Users\labadmin\Miniconda3\envs\phy2m\lib\site-packages\joblib\memory.py", line 734, in call
    output = self.func(*args, **kwargs)
  File "c:\users\labadmin\desktop\phy\phy821\phy\phy\apps\base.py", line 426, in get_spike_template_features
    template_amplitudes = tf[:, first_cluster]
IndexError: index 733 is out of bounds for axis 1 with size 715

```

I worked around this with 0e1f48fcb485aaf086c9bc281e47d3fb2921889a.

**Comment by rossant** [comment]
the bugs should be fixed, I added a new issue for the feature proposition
