### ISSUE TITLE
ImportError: No module named phylib.utils

### ISSUE THREAD

**Issue by IljaPilja** [cortex-lab/phy#923]
Hi,
after finally being able to run KiloSort and creating the params.py file, I continued the installation of Phy. I was able to set the correct Windows paths to Python 3.6 and pip 19.3.1 and simply followed the instructions for the terminal input. Everything seemed to be installing fine, without any error messages. For the last input:
'pip3 install git+https://github.com/cortex-lab/phylib.git' 
it installed the phylib folder under my \Local\Tmp\pip-d2o0jv-build\  path which I'm not sure is correct. I then changed directories to the params.py file and typed:
'phy template-gui params.py'

This lead to the following error message:

Traceback (most recent call last):
  File "c:\users\dsuchane\appdata\local\continuum\anaconda2\envs\phy2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\dsuchane\appdata\local\continuum\anaconda2\envs\phy2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dsuchane\AppData\Local\Continuum\Anaconda2\envs\phy2\Scripts\phy.exe\__main__.py", line 4, in <module>
  File "c:\users\dsuchane\appdata\local\continuum\anaconda2\envs\phy2\lib\site-packages\phy\__init__.py", line 18, in <module>
    from phylib.utils import Bunch
ImportError: No module named phylib.utils

Interesting as well is the fact that once I activate phy2 in the terminal and check which version of Python and pip I'm using, it tells me that it is using Python 2.7 and not the 3.6, even though prior to activating phy2 it calls Python 3.6.
Any help would be appreciated.
IljaPilja

**Comment by IljaPilja** [comment]
Well, the problem is sort of solved but I can only activate phy and not phy2. It seems under phy2 Python 2.7.17 is called while only under phy it calls Python 3.6.5. So I guess I have to work with phy instead of the newer phy2 version, unless someone can tell me how to fix this problem.
Thanks,
IljaPilja
