### ISSUE TITLE
gui error after upgrade to v2.0b1

### ISSUE THREAD

**Issue by v-hofmann** [cortex-lab/phy#963]
Hi Cyril, 

after trying to upgrade `(pip install phy --pre --upgrade)` to the release from early February, i am getting the following error regarding PyYAML deprecation when trying to start the gui - any idea what i can do? 

(phy2) D:\DATA_NPIX\2020-02-25_nP-Block\IMEC0\CAR\batch1>phy template-gui params.py c:\users\leckm\.conda\envs\phy2\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "c:\users\leckm\.conda\envs\phy2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\leckm\.conda\envs\phy2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\leckm\.conda\envs\phy2\Scripts\phy.exe\__main__.py", line 5, in <module>
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\apps\__init__.py", line 25, in <module>
    from .base import (  # noqa
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\apps\base.py", line 27, in <module>
    from phy.cluster._utils import RotatingProperty
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\cluster\__init__.py", line 9, in <module>
    from .views import *  # noqa
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\cluster\views\__init__.py", line 10, in <module>
    from .base import ManualClusteringView  # noqa
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\cluster\views\base.py", line 21, in <module>
    from phy.plot import PlotCanvas, NDC, extend_bounds
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\plot\__init__.py", line 18, in <module>
    from .plot import PlotCanvas
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\plot\plot.py", line 19, in <module>
    from .interact import Grid, Boxed, Stacked, Lasso
  File "c:\users\leckm\.conda\envs\phy2\lib\site-packages\phy\plot\interact.py", line 14, in <module>
    from phylib.utils.geometry import get_non_overlapping_boxes, get_closest_box
ImportError: cannot import name 'get_non_overlapping_boxes' from 'phylib.utils.geometry' (c:\users\leckm\.conda\envs\phy2\lib\site-packages\phylib\utils\geometry.py)

**Comment by v-hofmann** [comment]
i have re-created the phy environment in anaconda. That has solved the issue and the gui is running again.
