### ISSUE TITLE
PyQtWebEngine missing from requirements for dev version?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/phy#970]
Got this error, disappears after "pip install PyQtWebEngine" 

(phy2dev) D:\AD_0004\2019-10-04\p2MS_g0\p2MS_g0_imec0>phy teamplate-gui params.py
Traceback (most recent call last):
  File "C:\Users\nicks\Anaconda3\envs\phy2dev\Scripts\phy-script.py", line 11, in <module>
    load_entry_point('phy', 'console_scripts', 'phy')()
  File "C:\Users\nicks\Anaconda3\envs\phy2dev\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\nicks\Anaconda3\envs\phy2dev\lib\site-packages\pkg_resources\__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "C:\Users\nicks\Anaconda3\envs\phy2dev\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "C:\Users\nicks\Anaconda3\envs\phy2dev\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\nicks\dropbox\code\phy\phy\apps\__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "c:\users\nicks\dropbox\code\phy\phy\gui\__init__.py", line 6, in <module>
    from .qt import (
  File "c:\users\nicks\dropbox\code\phy\phy\gui\qt.py", line 41, in <module>
    from PyQt5.QtWebEngineWidgets import (QWebEngineView,  # noqa
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

**Comment by rossant** [comment]
This is needed on some environments indeed, I clarified the install instructions. Thanks!
